In [1]:
import numpy as np
import pandas as pd

In [72]:
latlong = pd.read_csv("/content/district wise centroids.csv")
census = pd.read_csv("/content/india-districts-census-2011.csv")

In [73]:
latlong.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   State      594 non-null    object
 1   District   594 non-null    object
 2   Latitude   594 non-null    float64
 3   Longitude  594 non-null    float64
dtypes: float64(2), object(2)
memory usage: 18.7+ KB

In [74]:
census.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Columns: 118 entries, District code to Total_Power_Parity
dtypes: int64(116), object(2)
memory usage: 590.1+ KB

In [7]:
for i in census.columns:
  print(i)

District code
State name
District name
Population
Male
Female
Literate
Male_Literate
Female_Literate
SC
Male_SC
Female_SC
ST
Male_ST
Female_ST
Workers
Male_Workers
Female_Workers
Main_Workers
Marginal_Workers
Non_Workers
Cultivator_Workers
Agricultural_Workers
Household_Workers
Other_Workers
Hindus
Muslims
Christians
Sikhs
Buddhists
Jains
Others_Religions
Religion_Not_Stated
LPG_or_PNG_Households
Housholds_with_Electric_Lighting
Households_with_Internet
Households_with_Computer
Rural_Households
Urban_Households
Households
Below_Primary_Education
Primary_Education
Middle_Education
Secondary_Education
Higher_Education
Graduate_Education
Other_Education
Literate_Education
Illiterate_Education
Total_Education
Age_Group_0_29
Age_Group_30_49
Age_Group_50
Age not stated
Households_with_Bicycle
Households_with_Car_Jeep_Van
Households_with_Radio_Transistor
Households_with_Scooter_Motorcycle_Moped
Households_with_Telephone_Mobile_Phone_Landline_only
Households_with_Telephone_Mobile_Phone_Mobile_only
Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car
Households_with_Television
Households_with_Telephone_Mobile_Phone
Households_with_Telephone_Mobile_Phone_Both
Condition_of_occupied_census_houses_Dilapidated_Households
Households_with_separate_kitchen_Cooking_inside_house
Having_bathing_facility_Total_Households
Having_latrine_facility_within_the_premises_Total_Households
Ownership_Owned_Households
Ownership_Rented_Households
Type_of_bathing_facility_Enclosure_without_roof_Households
Type_of_fuel_used_for_cooking_Any_other_Households
Type_of_latrine_facility_Pit_latrine_Households
Type_of_latrine_facility_Other_latrine_Households
Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households
Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households
Not_having_bathing_facility_within_the_premises_Total_Households
Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households
Main_source_of_drinking_water_Un_covered_well_Households
Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households
Main_source_of_drinking_water_Spring_Households
Main_source_of_drinking_water_River_Canal_Households
Main_source_of_drinking_water_Other_sources_Households
Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households
Location_of_drinking_water_source_Near_the_premises_Households
Location_of_drinking_water_source_Within_the_premises_Households
Main_source_of_drinking_water_Tank_Pond_Lake_Households
Main_source_of_drinking_water_Tapwater_Households
Main_source_of_drinking_water_Tubewell_Borehole_Households
Household_size_1_person_Households
Household_size_2_persons_Households
Household_size_1_to_2_persons
Household_size_3_persons_Households
Household_size_3_to_5_persons_Households
Household_size_4_persons_Households
Household_size_5_persons_Households
Household_size_6_8_persons_Households
Household_size_9_persons_and_above_Households
Location_of_drinking_water_source_Away_Households
Married_couples_1_Households
Married_couples_2_Households
Married_couples_3_Households
Married_couples_3_or_more_Households
Married_couples_4_Households
Married_couples_5__Households
Married_couples_None_Households
Power_Parity_Less_than_Rs_45000
Power_Parity_Rs_45000_90000
Power_Parity_Rs_90000_150000
Power_Parity_Rs_45000_150000
Power_Parity_Rs_150000_240000
Power_Parity_Rs_240000_330000
Power_Parity_Rs_150000_330000
Power_Parity_Rs_330000_425000
Power_Parity_Rs_425000_545000
Power_Parity_Rs_330000_545000
Power_Parity_Above_Rs_545000
Total_Power_Parity

In [75]:
cols = ["District code","State name","District name","Population","Male","Female","Literate",
        "Male_Literate","Female_Literate","Hindus","Muslims","Christians",
        "Sikhs","Buddhists","Jains","Others_Religions","LPG_or_PNG_Households","Housholds_with_Electric_Lighting",
"Households_with_Internet",
"Households_with_Computer"]

In [76]:
censusf = census[cols]

In [77]:
censusf["State name"] = censusf["State name"].replace({'NCT OF DELHI':"DELHI"})

<ipython-input-77-76cb3363d412>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  censusf["State name"] = censusf["State name"].replace({'NCT OF DELHI':"DELHI"})

In [78]:
np.sort(censusf["State name"].unique())

array(['ANDAMAN AND NICOBAR ISLANDS', 'ANDHRA PRADESH',
       'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHANDIGARH',
       'CHHATTISGARH', 'DADRA AND NAGAR HAVELI', 'DAMAN AND DIU', 'DELHI',
       'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH',
       'JAMMU AND KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA',
       'LAKSHADWEEP', 'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR',
       'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ORISSA', 'PONDICHERRY',
       'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TRIPURA',
       'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL'], dtype=object)

In [27]:
np.sort(latlong["State"].unique())

array(['Andaman and Nicobar', 'Andhra Pradesh', 'Arunachal Pradesh',
       'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh',
       'Dadra and Nagar Haveli', 'Daman and Diu', 'Delhi', 'Goa',
       'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir',
       'Jharkhand', 'Karnataka', 'Kerala', 'Lakshadweep',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Orissa', 'Puducherry', 'Punjab', 'Rajasthan',
       'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh', 'Uttaranchal',
       'West Bengal'], dtype=object)

In [79]:
state = {}
num=0
for i in np.sort(censusf["State name"].unique()):
  if i not in state:
    state[i] = np.sort(latlong["State"].unique())[num]
  num=num+1
print(state)

{'ANDAMAN AND NICOBAR ISLANDS': 'Andaman and Nicobar', 'ANDHRA PRADESH': 'Andhra Pradesh', 'ARUNACHAL PRADESH': 'Arunachal Pradesh', 'ASSAM': 'Assam', 'BIHAR': 'Bihar', 'CHANDIGARH': 'Chandigarh', 'CHHATTISGARH': 'Chhattisgarh', 'DADRA AND NAGAR HAVELI': 'Dadra and Nagar Haveli', 'DAMAN AND DIU': 'Daman and Diu', 'DELHI': 'Delhi', 'GOA': 'Goa', 'GUJARAT': 'Gujarat', 'HARYANA': 'Haryana', 'HIMACHAL PRADESH': 'Himachal Pradesh', 'JAMMU AND KASHMIR': 'Jammu and Kashmir', 'JHARKHAND': 'Jharkhand', 'KARNATAKA': 'Karnataka', 'KERALA': 'Kerala', 'LAKSHADWEEP': 'Lakshadweep', 'MADHYA PRADESH': 'Madhya Pradesh', 'MAHARASHTRA': 'Maharashtra', 'MANIPUR': 'Manipur', 'MEGHALAYA': 'Meghalaya', 'MIZORAM': 'Mizoram', 'NAGALAND': 'Nagaland', 'ORISSA': 'Orissa', 'PONDICHERRY': 'Puducherry', 'PUNJAB': 'Punjab', 'RAJASTHAN': 'Rajasthan', 'SIKKIM': 'Sikkim', 'TAMIL NADU': 'Tamil Nadu', 'TRIPURA': 'Tripura', 'UTTAR PRADESH': 'Uttar Pradesh', 'UTTARAKHAND': 'Uttaranchal', 'WEST BENGAL': 'West Bengal'}

In [80]:
censusf["State name"].replace(state,inplace=True)

<ipython-input-80-5d1a4de2f35c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  censusf["State name"].replace(state,inplace=True)

In [81]:
df = latlong.merge(censusf,left_on=["State","District"],right_on=["State name","District name"])

In [83]:
latlong.merge(censusf,left_on=["District"],right_on=["District name"])

,State,District,Latitude,Longitude,District code,State name,District name,Population,Male,Female,...,Muslims,Christians,Sikhs,Buddhists,Jains,Others_Religions,LPG_or_PNG_Households,Housholds_with_Electric_Lighting,Households_with_Internet,Households_with_Computer
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,Andhra Pradesh,Adilabad,2741239,1369597,1371642,...,275970,15422,1377,25510,617,322,194954,566108,5512,45202
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,Andhra Pradesh,Anantapur,4081148,2064495,2016653,...,443456,20463,932,341,1417,309,223016,897970,8606,48299
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,Andhra Pradesh,Chittoor,4174064,2090204,2083860,...,397870,24129,867,253,1322,358,324406,944555,13763,67087
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,Andhra Pradesh,East Godavari,5154296,2569688,2584608,...,77777,77825,738,413,4149,403,479914,1297273,22411,93784
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,Andhra Pradesh,Guntur,4887813,2440521,2447292,...,559770,89763,764,323,3282,332,648568,1186028,19383,80434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,332,West Bengal,Maldah,3988845,2051541,1937304,...,2045151,13209,747,359,639,7929,54213,297716,5357,63525
513,West Bengal,Murshidabad,24.259507,88.168169,333,West Bengal,Murshidabad,7103807,3627564,3476243,...,4707573,18102,766,348,3037,7429,92742,541169,7951,79729
514,West Bengal,Nadia,23.564110,88.582930,336,West Bengal,Nadia,5167600,2653768,2513832,...,1382682,33835,849,514,281,16893,168314,623729,12787,77210
515,West Bengal,Puruliya,23.254192,86.396853,340,West Bengal,Puruliya,2930115,1496996,1433119,...,227249,8646,622,209,3052,309029,30675,189889,3551,32862
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,330,West Bengal,Uttar Dinajpur,3007134,1551066,1456068,...,1501170,16702,477,432,1324,1622,39138,199307,2883,31210

In [41]:
latlong[latlong["District"].duplicated()]

                State    District   Latitude  Longitude
132           Gujarat    Junagadh  20.929523  70.547339
167  Himachal Pradesh    Bilaspur  31.378042  76.653161
308       Maharashtra  Aurangabad  20.097923  75.320722
329       Maharashtra     Raigarh  18.453258  73.009061
523     Uttar Pradesh    Hamirpur  25.738158  79.826195

In [40]:
censusf["District name"].duplicated()

6

In [45]:
latlong[latlong["District"]=="Hamirpur"]

                State  District   Latitude  Longitude
169  Himachal Pradesh  Hamirpur  31.676685  76.497671
523     Uttar Pradesh  Hamirpur  25.738158  79.826195

In [49]:
df.drop(columns=["State name","District name"],inplace=True)

In [84]:
state

{'ANDAMAN AND NICOBAR ISLANDS': 'Andaman and Nicobar',
 'ANDHRA PRADESH': 'Andhra Pradesh',
 'ARUNACHAL PRADESH': 'Arunachal Pradesh',
 'ASSAM': 'Assam',
 'BIHAR': 'Bihar',
 'CHANDIGARH': 'Chandigarh',
 'CHHATTISGARH': 'Chhattisgarh',
 'DADRA AND NAGAR HAVELI': 'Dadra and Nagar Haveli',
 'DAMAN AND DIU': 'Daman and Diu',
 'DELHI': 'Delhi',
 'GOA': 'Goa',
 'GUJARAT': 'Gujarat',
 'HARYANA': 'Haryana',
 'HIMACHAL PRADESH': 'Himachal Pradesh',
 'JAMMU AND KASHMIR': 'Jammu and Kashmir',
 'JHARKHAND': 'Jharkhand',
 'KARNATAKA': 'Karnataka',
 'KERALA': 'Kerala',
 'LAKSHADWEEP': 'Lakshadweep',
 'MADHYA PRADESH': 'Madhya Pradesh',
 'MAHARASHTRA': 'Maharashtra',
 'MANIPUR': 'Manipur',
 'MEGHALAYA': 'Meghalaya',
 'MIZORAM': 'Mizoram',
 'NAGALAND': 'Nagaland',
 'ORISSA': 'Orissa',
 'PONDICHERRY': 'Puducherry',
 'PUNJAB': 'Punjab',
 'RAJASTHAN': 'Rajasthan',
 'SIKKIM': 'Sikkim',
 'TAMIL NADU': 'Tamil Nadu',
 'TRIPURA': 'Tripura',
 'UTTAR PRADESH': 'Uttar Pradesh',
 'UTTARAKHAND': 'Uttaranchal',
 'WEST BENGAL': 'West Bengal'}

In [85]:
df.State.unique()

array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
       'Chandigarh', 'Chhattisgarh', 'Daman and Diu', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
       'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Meghalaya', 'Mizoram', 'Nagaland', 'Orissa', 'Puducherry',
       'Punjab', 'Rajasthan', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh',
       'Uttaranchal', 'West Bengal'], dtype=object)

In [86]:
df['sex_ratio'] = round((df['Female']/df['Male'])*100)

In [87]:
df['literacy_rate'] = round((df['Literate']/df['Population'])*100)

In [88]:
df.to_csv("census.csv",index=False)

In [89]:
list(df["State"].unique()).insert(0,"OverAll India")

In [94]:
states = df["State"].unique().tolist()
states.insert(0, "OverAll India")

In [95]:
states

['OverAll India',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Daman and Diu',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Orissa',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'Uttaranchal',
 'West Bengal']

In [97]:
df.shape

(505, 26)